### ISSUE TITLE
Structs from runng do not implement `Debug` and might benefit from some other nice Traits.

### ISSUE THREAD

**Issue by najamelan** [jeikabu/runng#25]
Right now if a struct contains for example a `protocol::pair1::Pair1` it can't derive `Debug` because `Pair1` doesn't implement it. It is generally accepted to more or less always derive or implement at least `Debug` for all `pub struct`s.

Others that might be useful can be found in [the rust book](https://doc.rust-lang.org/book/appendix-03-derivable-traits.html). `Eq` might also make sense for a socket. For the difference between `Eq` and `PartialEq`, see [here](https://users.rust-lang.org/t/what-is-the-difference-between-eq-and-partialeq/15751). 

Some traits are handy if it makes sense, like `Copy`, but they have implications for the future. If you later add a non-`Copy` property to your struct, you will have to break the API by removing `Copy` and instances will be implicitly copied on the stack which might not always be a good idea. However `Clone` is explicit and might be a good idea.

**Comment by najamelan** [comment]
I forgot to mention. Sometimes you have to explicitly set structs to be not `Send` or `Sync` if they are not threadsafe. Especially when working with C code it's good to think about this for every structure.

**Comment by jeikabu** [comment]
This one is trickier.

I've been using `#derive[]` sparingly on an "as-needed" basis.  For example, `NngError` has [Clone/Copy/Debug/PartialEq](https://github.com/jeikabu/runng/blob/master/runng/src/result.rs#L8).

Most of the other structs are wrappers around C FFI bindings and __not__ safe for Copy/Clone.  Pretty much all of them have a function that needs to be called on `Drop` (`nng_msg_free`, `nng_close`, etc.).  As much as possible I'd like to use Rust to enforce "correct" usage, but I haven't really settled on the best way to deal with this:
- Sockets currently use an `Arc` ([code](https://github.com/jeikabu/runng/blob/master/runng/src/socket.rs#L9))
- Stats does it with lifetimes ([code](https://github.com/jeikabu/runng/blob/master/runng/src/stats.rs#L127))

For example, once you've called [create_async_context()](https://github.com/jeikabu/runng/blob/master/runng/src/protocol/mod.rs#L58) I don't think it's safe to use the socket, so the socket should probably get "consumed" (i.e. `create_async_context(self)` instead of `create_async_context(&self)`).  But I need to ask the nng author to be sure.

But I think you're right that there could be some improvements:
- [I added `impl Clone for NngMsg`](https://github.com/jeikabu/runng/blob/dev/runng/src/msg/msg.rs#L154) (which just calls `nng_msg_dup`)
- I think `Debug` is safe everywhere so I'll look at sprinkling it around

**Comment by najamelan** [comment]
Thanks for looking into this. This makes me wonder, in async code it is common to use closures and thus often one needs to "clone" things. In the little test app I posted, I thus end up cloning a `protocol::pair1::Pair1` even though it's not in polyamorous mode. Is that a problem?

**Comment by jeikabu** [comment]
It's ok to clone it, it won't get closed until the last reference goes away.  The `Arc` provides Send/Sync.

At the moment there's only `impl Send for NngAio` because I tend to write:
```rust
let a = factory.pair_open()?.listen(&url)?;
let b = factory.pair_open()?.dial(&url)?;

let a_thread = thread::spawn(move || -> NngReturn {
    let mut ctx = a.create_async_context()?;
    //...
});
```

I don't plan to use the synchronous functions like `SendMsg::send()` so I've not thought about that part of the API much.
